Clockwork.config:AddToSystem("AttributeProgressionScale", "scale_attribute_progress", "AttributeProgressionScaleDesc");
Clockwork.config:AddToSystem("MessagesMustSeePlayer", "messages_must_see_player", "MessagesMustSeePlayerDesc");
Clockwork.config:AddToSystem("StartingAttributePoints", "default_attribute_points", "StartingAttributePointsDesc");
Clockwork.config:AddToSystem("ClockworkIntroductionEnabled", "clockwork_intro_enabled", "ClockworkIntroductionEnabledDesc");
Clockwork.config:AddToSystem("HealthRegenerationEnabled", "health_regeneration_enabled", "HealthRegenerationEnabledDesc");
Clockwork.config:AddToSystem("PropProtectionEnabled", "enable_prop_protection", "PropProtectionEnabledDesc");
Clockwork.config:AddToSystem("UseLocalMachineDate", "use_local_machine_date", "UseLocalMachineDateDesc");
Clockwork.config:AddToSystem("UseLocalMachineTime", "use_local_machine_time", "UseLocalMachineTimeDesc");
Clockwork.config:AddToSystem("UseKeyOpensEntityMenus", "use_opens_entity_menus", "UseKeyOpensEntityMenusDesc");
Clockwork.config:AddToSystem("ShootAfterRaiseDelay", "shoot_after_raise_time", "ShootAfterRaiseDelayDesc");
Clockwork.config:AddToSystem("UseClockworksAdminSystem", "use_own_group_system", "UseClockworksAdminSystemDesc");
Clockwork.config:AddToSystem("SavedRecognisedNames", "save_recognised_names", "SavedRecognisedNamesDesc");
Clockwork.config:AddToSystem("SaveAttributeBoosts", "save_attribute_boosts", "SaveAttributeBoostsDesc");
Clockwork.config:AddToSystem("RagdollDamageImmunityTime", "ragdoll_immunity_time", "RagdollDamageImmunityTimeDesc");
Clockwork.config:AddToSystem("MaxTraitPoints", "max_trait_points", "MaxTraitPointsDesc");
Clockwork.config:AddToSystem("AdditionalCharacterCount", "additional_characters", "AdditionalCharacterCountDesc");
Clockwork.config:AddToSystem("ClassChangingInterval", "change_class_interval", "ClassChangingIntervalDesc", 0, 7200);
Clockwork.config:AddToSystem("SprintingLowersWeapon", "sprint_lowers_weapon", "SprintingLowersWeaponDesc");
Clockwork.config:AddToSystem("WeaponRaisingSystemEnabled", "raised_weapon_system", "WeaponRaisingSystemEnabledDesc");
Clockwork.config:AddToSystem("PropKillProtectionEnabled", "prop_kill_protection", "PropKillProtectionEnabledDesc");
Clockwork.config:AddToSystem("UseSmoothServerRates", "use_smooth_rates", "UseSmoothServerRatesDesc");
Clockwork.config:AddToSystem("UseMediumPerformanceServerRates", "use_optimised_rates", "UseMediumPerformanceServerRatesDesc");
Clockwork.config:AddToSystem("UseLagFreeServerRates", "use_lag_free_rates", "UseLagFreeServerRatesDesc");
Clockwork.config:AddToSystem("GeneratorInterval", "generator_interval", "GeneratorIntervalDesc", 0, 7200);
Clockwork.config:AddToSystem("GravityGunPuntEnabled", "enable_gravgun_punt", "GravityGunPuntEnabledDesc");
Clockwork.config:AddToSystem("DefaultInventoryWeight", "default_inv_weight", "DefaultInventoryWeightDesc");
Clockwork.config:AddToSystem("DefaultInventorySpace", "default_inv_space", "DefaultInventorySpaceDesc");
Clockwork.config:AddToSystem("DataSaveInterval", "save_data_interval", "DataSaveIntervalDesc", 0, 7200);
Clockwork.config:AddToSystem("ViewPunchOnDamage", "damage_view_punch", "ViewPunchOnDamageDesc");
Clockwork.config:AddToSystem("UnrecognisedName", "unrecognised_name", "UnrecognisedNameDesc");
Clockwork.config:AddToSystem("ForceLanguage", "force_language", "ForceLanguageDesc");
Clockwork.config:AddToSystem("LimbDamageSystemEnabled", "limb_damage_system", "LimbDamageSystemEnabledDesc");
Clockwork.config:AddToSystem("FallDamageScale", "scale_fall_damage", "FallDamageScaleDesc");
Clockwork.config:AddToSystem("StartingCurrency", "default_cash", "StartingCurrencyDesc", 0, 10000);
Clockwork.config:AddToSystem("ArmorAffectsChestOnly", "armor_chest_only", "ArmorAffectsChestOnlyDesc");
Clockwork.config:AddToSystem("MinimumPhysicalDescriptionLength", "minimum_physdesc", "MinimumPhysicalDescriptionLengthDesc", 0, 128);
Clockwork.config:AddToSystem("WoodBreaksFall", "wood_breaks_fall", "WoodBreaksFallDesc");
Clockwork.config:AddToSystem("VignetteEnabled", "enable_vignette", "VignetteEnabledDesc");
Clockwork.config:AddToSystem("HeartbeatSoundsEnabled", "enable_heartbeat", "HeartbeatSoundsEnabledDesc");
Clockwork.config:AddToSystem("CrosshairEnabled", "enable_crosshair", "CrosshairEnabledDesc");
Clockwork.config:AddToSystem("FreeAimingEnabled", "use_free_aiming", "FreeAimingEnabledDesc");
Clockwork.config:AddToSystem("RecogniseSystemEnabled", "recognise_system", "RecogniseSystemEnabledDesc");
Clockwork.config:AddToSystem("CurrencyEnabled", "cash_enabled", "CurrencyEnabledDesc");
Clockwork.config:AddToSystem("DefaultPhysicalDescription", "default_physdesc", "DefaultPhysicalDescriptionDesc");
Clockwork.config:AddToSystem("ChestDamageScale", "scale_chest_dmg", "ChestDamageScaleDesc");
Clockwork.config:AddToSystem("CorpseDecayTime", "body_decay_time", "CorpseDecayTimeDesc", 0, 7200);
Clockwork.config:AddToSystem("BannedDisconnectMessage", "banned_message", "BannedDisconnectMessageDesc");
Clockwork.config:AddToSystem("WagesInterval", "wages_interval", "WagesIntervalDesc", 0, 7200);
Clockwork.config:AddToSystem("PropCostScale", "scale_prop_cost", "PropCostScaleDesc");
Clockwork.config:AddToSystem("FadeNPCCorpses", "fade_dead_npcs", "FadeNPCCorpsesDesc");
Clockwork.config:AddToSystem("CashWeight", "cash_weight", "CashWeightDesc", 0, 100, 3);
Clockwork.config:AddToSystem("CashSpace", "cash_space", "CashSpaceDesc", 0, 100, 3);
Clockwork.config:AddToSystem("HeadDamageScale", "scale_head_dmg", "HeadDamageScaleDesc");
Clockwork.config:AddToSystem("BlockInventoryBinds", "block_inv_binds", "BlockInventoryBindsDesc");
Clockwork.config:AddToSystem("LimbDamageScale", "scale_limb_dmg", "LimbDamageScaleDesc");
Clockwork.config:AddToSystem("TargetIDDelay", "target_id_delay", "TargetIDDelayDesc");
Clockwork.config:AddToSystem("HeadbobEnabled", "enable_headbob", "HeadbobEnabledDesc");
Clockwork.config:AddToSystem("ChatCommandPrefix", "command_prefix", "ChatCommandPrefixDesc");
Clockwork.config:AddToSystem("CrouchWalkSpeed", "crouched_speed", "CrouchWalkSpeedDesc", 0, 1024);
Clockwork.config:AddToSystem("MaximumChatLength", "max_chat_length", "MaximumChatLengthDesc", 0, 1024);
Clockwork.config:AddToSystem("StartingFlags", "default_flags", "StartingFlagsDesc");
Clockwork.config:AddToSystem("PlayerSprayEnabled", "disable_sprays", "PlayerSprayEnabledDesc");
Clockwork.config:AddToSystem("HintInterval", "hint_interval", "HintIntervalDesc", 0, 7200);
Clockwork.config:AddToSystem("OutOfCharacterChatInterval", "ooc_interval", "OutOfCharacterChatIntervalDesc", 0, 7200);
Clockwork.config:AddToSystem("MinuteTime", "minute_time", "MinuteTimeDesc", 0, 7200);
Clockwork.config:AddToSystem("DoorUnlockInterval", "unlock_time", "DoorUnlockIntervalDesc", 0, 7200);
Clockwork.config:AddToSystem("VoiceChatEnabled", "voice_enabled", "VoiceChatEnabledDesc");
Clockwork.config:AddToSystem("LocalVoiceChat", "local_voice", "LocalVoiceChatDesc");
Clockwork.config:AddToSystem("TalkRadius", "talk_radius", "TalkRadiusDesc", 0, 4096);
Clockwork.config:AddToSystem("GiveHands", "give_hands", "GiveHandsDesc");
Clockwork.config:AddToSystem("CustomWeaponColor", "custom_weapon_color", "CustomWeaponColorDesc");
Clockwork.config:AddToSystem("GiveKeys", "give_keys", "GiveKeysDesc");
Clockwork.config:AddToSystem("WagesName", "wages_name", "WagesNameDesc");
Clockwork.config:AddToSystem("JumpPower", "jump_power", "JumpPowerDesc", 0, 1024);
Clockwork.config:AddToSystem("RespawnDelay", "spawn_time", "RespawnDelayDesc", 0, 7200);
Clockwork.config:AddToSystem("MaximumWalkSpeed", "walk_speed", "MaximumWalkSpeedDesc", 0, 1024);
Clockwork.config:AddToSystem("MaximumRunSpeed", "run_speed", "MaximumRunSpeedDesc", 0, 1024);
Clockwork.config:AddToSystem("DoorPrice", "door_cost", "DoorPriceDesc");
Clockwork.config:AddToSystem("DoorLockInterval", "lock_time", "DoorLockIntervalDesc", 0, 7200);
Clockwork.config:AddToSystem("MaximumOwnableDoors", "max_doors", "MaximumOwnableDoorsDesc");
Clockwork.config:AddToSystem("EnableSpaceSystem", "enable_space_system", "EnableSpaceSystemDesc");
Clockwork.config:AddToSystem("DrawIntroBars", "draw_intro_bars", "DrawIntroBarsDesc");
Clockwork.config:AddToSystem("EnableJogging", "enable_jogging", "EnableJoggingDesc");
Clockwork.config:AddToSystem("EnableLOOCIcons", "enable_looc_icons", "EnableLOOCIconsDesc");
Clockwork.config:AddToSystem("ShowBusinessMenu", "show_business", "ShowBusinessMenuDesc");
Clockwork.config:AddToSystem("EnableChatMultiplier", "chat_multiplier", "EnableChatMultiplierDesc");
Clockwork.config:AddToSystem("SteamAPIKey", "steam_api_key", "SteamAPIKeyDesc");
Clockwork.config:AddToSystem("EnableMapPropsPhysgrab", "enable_map_props_physgrab", "EnableMapPropsPhysgrabDesc");
Clockwork.config:AddToSystem("EntityUseCooldown", "entity_handle_time", "EntityUseCooldownDesc", 0, 1, 3);
Clockwork.config:AddToSystem("EnableSmoothSprint", "player_should_smooth_sprint", "EnableSmoothSprintDesc");
Clockwork.config:AddToSystem("EnableQuickRaise", "quick_raise_enabled", "EnableQuickRaiseDesc");
Clockwork.config:AddToSystem("PlayersChangeThemes", "modify_themes", "PlayersChangeThemesDesc");
Clockwork.config:AddToSystem("DefaultTheme", "default_theme", "DefaultThemeDesc");
Clockwork.config:AddToSystem("EnableDiseases", "enable_disease", "EnableDiseasesDesc");
Clockwork.config:AddToSystem("DiseaseInterval", "disease_interval", "DiseaseIntervalDesc");
Clockwork.config:AddToSystem("EnableIronsights", "enable_ironsights", "EnableIronsightsDesc");
Clockwork.config:AddToSystem("IronsightsSpreadReduction", "ironsights_spread", "IronsightsSpreadReductionDesc", 0, 1, 3);
Clockwork.config:AddToSystem("IronsightsSlowAmount", "ironsights_slow", "IronsightsSlowAmountDesc", 0, 1, 3);
Clockwork.config:AddToSystem("MaxCharName", "max_char_name", "MaxCharNameDesc", 1, 100);
Clockwork.config:AddToSystem("CraftingDescription", "description_crafting", "CraftingDescriptionDesc");
Clockwork.config:AddToSystem("CraftingEnabled", "crafting_menu_enabled", "CraftingEnabledDesc");
